// packages/preact/src/components/span/ui/Span.tsx
import { SpanComponent } from '@otmozorok/wc';
import { WCTAG } from '@otmozorok/wc/consts';
import { ISpanProps } from '../model';

customElements.get(WCTAG.Span) || customElements.define(WCTAG.Span, SpanComponent);

export function Span({ appearance, caps, children, ...props }: ISpanProps) {
  return (
    <wc-span appearance={appearance} caps={caps || undefined} {...props}>
      {children}
    </wc-span>
  );
}

// packages/vue/src/components/span/ui/Span.vue
<template>
  <wc-span :appearance="$props.appearance" :caps="$props.caps || undefined">
    <slot></slot>
  </wc-span>
</template>

<script lang="ts" setup>
import { SpanComponent } from '@otmozorok/wc';
import { APPEARANCE, WCTAG } from '@otmozorok/wc/consts';
import { ISpanProps } from '../model';

customElements.get(WCTAG.Span) || customElements.define(WCTAG.Span, SpanComponent);

withDefaults(defineProps<ISpanProps>(), {
  appearance: APPEARANCE.Themed,
});
</script>
