// packages/react/src/components/headline/ui/Headline.tsx
import { HeadlineComponent } from '@otmozorok/wc';
import { SIZE, WCTAG } from '@otmozorok/wc/consts';
import type { IHeadlineProps } from '../model';

customElements.get(WCTAG.Headline) || customElements.define(WCTAG.Headline, HeadlineComponent);

export const Headline: React.FC<React.PropsWithChildren<IHeadlineProps>> = ({
  children,
  caps,
  size,
  appearance,
  ...props
}) => {
  return (
    <wc-headline size={size} appearance={appearance} caps={caps} {...props}>
      {children}
    </wc-headline>
  );
};

// packages/svelte/src/components/headline/ui/Headline.svelte
<script lang="ts">
  import { HeadlineComponent } from '@otmozorok/wc';
  import { WCTAG } from '@otmozorok/wc/consts';
  import type { IHeadlineProps } from '../model';

  customElements.get(WCTAG.Headline) || customElements.define(WCTAG.Headline, HeadlineComponent);

  const { children, appearance, size, caps, ...props }: IHeadlineProps = $props();
</script>

<wc-headline {appearance} {size} caps={caps || undefined} {...props}>
  {@render children?.()}
</wc-headline>
