// packages/preact/src/components/headline/ui/Headline.tsx
import { HeadlineComponent } from '@otmozorok/wc';
import { WCTAG } from '@otmozorok/wc/consts';
import { IHeadlineProps } from '../model';

customElements.get(WCTAG.Headline) || customElements.define(WCTAG.Headline, HeadlineComponent);

export function Headline({ children, appearance, size, caps, ...props }: IHeadlineProps) {
  return (
    <wc-headline appearance={appearance} size={size} caps={caps || undefined} {...props}>
      {children}
    </wc-headline>
  );
}

// packages/vue/src/components/headline/ui/Headline.vue
<template>
  <wc-headline :size="$props.size" :appearance="$props.appearance" :caps="$props.caps || undefined">
    <slot></slot>
  </wc-headline>
</template>

<script lang="ts" setup>
import { HeadlineComponent } from '@otmozorok/wc';
import { WCTAG } from '@otmozorok/wc/consts';
import { IHeadlineProps } from '../model';

customElements.get(WCTAG.Headline) || customElements.define(WCTAG.Headline, HeadlineComponent);

defineProps<IHeadlineProps>();
</script>
