// packages/svelte/src/components/headline/ui/Headline.svelte
<script lang="ts">
  import { HeadlineComponent } from '@otmozorok/wc';
  import { WCTAG } from '@otmozorok/wc/consts';
  import type { IHeadlineProps } from '../model';

  customElements.get(WCTAG.Headline) || customElements.define(WCTAG.Headline, HeadlineComponent);

  const { children, appearance, size, caps, ...props }: IHeadlineProps = $props();
</script>

<wc-headline {appearance} {size} caps={caps || undefined} {...props}>
  {@render children?.()}
</wc-headline>

// packages/preact/src/components/headline/ui/Headline.tsx
import { HeadlineComponent } from '@otmozorok/wc';
import { WCTAG } from '@otmozorok/wc/consts';
import { IHeadlineProps } from '../model';

customElements.get(WCTAG.Headline) || customElements.define(WCTAG.Headline, HeadlineComponent);

export function Headline({ children, appearance, size, caps, ...props }: IHeadlineProps) {
  return (
    <wc-headline appearance={appearance} size={size} caps={caps || undefined} {...props}>
      {children}
    </wc-headline>
  );
}
