// packages/vue/src/components/button/Button.vue
<template>
  <wc-button type="button" :class="classes" @click="onClick" :style="style">{{ label }}</wc-button>
</template>

<script lang="ts" setup>
import { computed } from 'vue';
import { ButtonComponent, WCTAG } from '@otmozorok/wc';

customElements.get(WCTAG.Button) || customElements.define(WCTAG.Button, ButtonComponent);

const props = withDefaults(
  defineProps<{
    /**
     * The label of the button
     */
    label: string;
    /**
     * primary or secondary button
     */
    primary?: boolean;
    /**
     * size of the button
     */
    size?: 'small' | 'medium' | 'large';
    /**
     * background color of the button
     */
    backgroundColor?: string;
  }>(),
  { primary: false }
);

const emit = defineEmits<{
  (e: 'click', id: number): void;
}>();

const classes = computed(() => ({
  'storybook-button': true,
  'storybook-button--primary': props.primary,
  'storybook-button--secondary': !props.primary,
  [`storybook-button--${props.size || 'medium'}`]: true,
}));

const style = computed(() => ({
  backgroundColor: props.backgroundColor,
}));

const onClick = () => {
  emit('click', 1);
};
</script>

// packages/svelte/src/components/button/Button.svelte
<script lang="ts">
  import { ButtonComponent, WCTAG } from '@otmozorok/wc';
  import type { Snippet } from 'svelte';

  customElements.get(WCTAG.Button) || customElements.define(WCTAG.Button, ButtonComponent);

  interface Props {
    size?: 'small' | 'medium' | 'large';
    onclick?: () => void;
    children: Snippet;
  }

  const { children, ...props }: Props = $props();
</script>

<wc-button {...props}>
  {@render children?.()}
</wc-button>
