// packages/react/src/components/span/ui/Span.tsx
import { SpanComponent } from '@otmozorok/wc';
import { WCTAG } from '@otmozorok/wc/consts';
import type { ISpanProps } from '../model';

customElements.get(WCTAG.Span) || customElements.define(WCTAG.Span, SpanComponent);

export function Span({ appearance, caps, children, ...props }: ISpanProps) {
  return (
    <wc-span appearance={appearance} caps={caps || undefined} {...props}>
      {children}
    </wc-span>
  );
}

// packages/svelte/src/components/span/ui/Span.svelte
<script lang="ts">
  import { SpanComponent } from '@otmozorok/wc';
  import { WCTAG } from '@otmozorok/wc/consts';
  import type { ISpanProps } from '../model';

  customElements.get(WCTAG.Span) || customElements.define(WCTAG.Span, SpanComponent);

  const { children, appearance, caps, ...props }: ISpanProps = $props();
</script>

<wc-span {appearance} caps={caps || undefined} {...props}>
  {@render children?.()}
</wc-span>
