// packages/react/src/components/button/ui/Button.tsx
import { ButtonComponent, LoaderComponent } from '@otmozorok/wc';
import { APPEARANCE, MODE, SIZE, WCTAG } from '@otmozorok/wc/consts';
import { useRef, useEffect } from 'react';
import type { IButtonProps } from '../model';

customElements.get(WCTAG.Button) || customElements.define(WCTAG.Button, ButtonComponent);
customElements.get(WCTAG.Loader) || customElements.define(WCTAG.Loader, LoaderComponent);

export function Button({
  children,
  appearance = APPEARANCE.Themed,
  mode = MODE.Primary,
  size = SIZE.Medium,
  loading,
  fullWidth,
  onClick,
  ...props
}: IButtonProps) {
  const ref = useRef<ButtonComponent>(null);

  useEffect(() => {
    if (!ref.current) return;

    function handleClick(e: Event) {
      e.stopPropagation();
      onClick?.();
    }

    ref.current.addEventListener('click', handleClick);

    return () => {
      ref.current?.removeEventListener('click', handleClick);
    };
  }, [onClick]);

  return (
    <wc-button
      ref={ref}
      appearance={appearance}
      mode={mode}
      size={size}
      loading={loading ? true : undefined}
      full-width={fullWidth ? true : undefined}
      {...props}
    >
      {children}
    </wc-button>
  );
}

// packages/vue/src/components/button/ui/Button.vue
<template>
  <wc-button
    :appearance="$props.appearance"
    :size="$props.size"
    :mode="$props.mode"
    :loading="$props.loading || undefined"
    :full-width="$props.fullWidth || undefined"
  >
    <slot></slot>
  </wc-button>
</template>

<script lang="ts" setup>
import { ButtonComponent, LoaderComponent } from '@otmozorok/wc';
import { APPEARANCE, MODE, SIZE, WCTAG } from '@otmozorok/wc/consts';
import { IButtonProps } from '../model';

customElements.get(WCTAG.Button) || customElements.define(WCTAG.Button, ButtonComponent);
customElements.get(WCTAG.Loader) || customElements.define(WCTAG.Loader, LoaderComponent);

withDefaults(defineProps<IButtonProps>(), {
  mode: MODE.Primary,
  appearance: APPEARANCE.Themed,
  size: SIZE.Medium,
});
</script>
