// packages/svelte/src/components/button/ui/Button.svelte
<script lang="ts">
  import { ButtonComponent, LoaderComponent } from '@otmozorok/wc';
  import { WCTAG } from '@otmozorok/wc/consts';
  import type { IButtonProps } from '../model';

  customElements.get(WCTAG.Button) || customElements.define(WCTAG.Button, ButtonComponent);
  customElements.get(WCTAG.Loader) || customElements.define(WCTAG.Loader, LoaderComponent);

  const { children, onclick, appearance, mode, size, loading, fullWidth, ...rest }: IButtonProps =
    $props();
</script>

<!-- svelte-ignore event_directive_deprecated -->
<wc-button
  {appearance}
  {mode}
  {size}
  loading={loading || undefined}
  full-width={fullWidth || undefined}
  on:click={onclick}
  {...rest}
>
  {@render children?.()}
</wc-button>

// packages/preact/src/components/button/ui/Button.tsx
import { ButtonComponent, LoaderComponent } from '@otmozorok/wc';
import { APPEARANCE, MODE, SIZE, WCTAG } from '@otmozorok/wc/consts';
import { IButtonProps } from '../model';

customElements.get(WCTAG.Button) || customElements.define(WCTAG.Button, ButtonComponent);
customElements.get(WCTAG.Loader) || customElements.define(WCTAG.Loader, LoaderComponent);

export function Button({
  children,
  appearance = APPEARANCE.Themed,
  mode = MODE.Primary,
  size = SIZE.Medium,
  loading,
  fullWidth,
  ...props
}: IButtonProps) {
  return (
    <wc-button
      appearance={appearance}
      mode={mode}
      size={size}
      loading={loading || undefined}
      full-width={fullWidth || undefined}
      {...props}
    >
      {children}
    </wc-button>
  );
}
