// packages/vue/src/components/paragraph/ui/Paragraph.vue
<template>
  <wc-paragraph :appearance="$props.appearance" :caps="$props.caps || undefined">
    <slot></slot>
  </wc-paragraph>
</template>

<script lang="ts" setup>
import { ParagraphComponent } from '@otmozorok/wc';
import { APPEARANCE, WCTAG } from '@otmozorok/wc/consts';
import { IParagraphProps } from '../model';

customElements.get(WCTAG.Paragraph) || customElements.define(WCTAG.Paragraph, ParagraphComponent);

withDefaults(defineProps<IParagraphProps>(), {
  appearance: APPEARANCE.Themed,
});
</script>

// packages/preact/src/components/paragraph/ui/Paragraph.tsx
import { ParagraphComponent } from '@otmozorok/wc';
import { WCTAG } from '@otmozorok/wc/consts';
import { IParagraphProps } from '../model';

customElements.get(WCTAG.Paragraph) || customElements.define(WCTAG.Paragraph, ParagraphComponent);

export function Paragraph({ children, appearance, caps, ...props }: IParagraphProps) {
  return (
    <wc-paragraph appearance={appearance} caps={caps || undefined} {...props}>
      {children}
    </wc-paragraph>
  );
}
