// packages/react/src/components/avatar/ui/Avatar.tsx
import { AvatarComponent, IconComponent } from '@otmozorok/wc';
import { COLOR, SHAPE, WCTAG } from '@otmozorok/wc/consts';
import type { IAvatarProps } from '../model';

customElements.get(WCTAG.Avatar) || customElements.define(WCTAG.Avatar, AvatarComponent);
customElements.get(WCTAG.Icon) || customElements.define(WCTAG.Icon, IconComponent);

export const Avatar: React.FC<React.PropsWithChildren<IAvatarProps>> = ({
  children,
  color,
  shape,
  sizeNumber,
  ...props
}) => {
  return (
    <wc-avatar color={color} shape={shape} size-number={sizeNumber} {...props}>
      {children}
    </wc-avatar>
  );
};

// packages/svelte/src/components/avatar/ui/Avatar.svelte
<script lang="ts">
  import { AvatarComponent } from '@otmozorok/wc';
  import { WCTAG } from '@otmozorok/wc/consts';
  import type { IAvatarProps } from '../model';

  customElements.get(WCTAG.Avatar) || customElements.define(WCTAG.Avatar, AvatarComponent);

  const { children, sizeNumber, color, shape, ...props }: IAvatarProps = $props();
</script>

<wc-avatar size-number={sizeNumber} {color} {shape} {...props}>
  {@render children?.()}
</wc-avatar>
