// packages/preact/src/components/avatar/ui/Avatar.tsx
import { AvatarComponent, IconComponent } from '@otmozorok/wc';
import { COLOR, SHAPE, WCTAG } from '@otmozorok/wc/consts';
import { IAvatarProps } from '../model';

customElements.get(WCTAG.Avatar) || customElements.define(WCTAG.Avatar, AvatarComponent);
customElements.get(WCTAG.Icon) || customElements.define(WCTAG.Icon, IconComponent);

export function Avatar({
  color = COLOR.Green,
  sizeNumber = 3,
  shape = SHAPE.Circle,
  children,
}: IAvatarProps) {
  return (
    <wc-avatar color={color} size-number={sizeNumber} shape={shape}>
      {children}
    </wc-avatar>
  );
}

// packages/svelte/src/components/avatar/ui/Avatar.svelte
<script lang="ts">
  import { AvatarComponent } from '@otmozorok/wc';
  import { WCTAG } from '@otmozorok/wc/consts';
  import type { IAvatarProps } from '../model';

  customElements.get(WCTAG.Avatar) || customElements.define(WCTAG.Avatar, AvatarComponent);

  const { children, sizeNumber, color, shape, ...props }: IAvatarProps = $props();
</script>

<wc-avatar size-number={sizeNumber} {color} {shape} {...props}>
  {@render children?.()}
</wc-avatar>
