// packages/solid/src/components/banner/ui/Banner.tsx
import { BannerComponent } from '@otmozorok/wc';
import { APPEARANCE, WCTAG } from '@otmozorok/wc/consts';
import { mergeProps, type ParentProps, splitProps } from 'solid-js';
import { IBannerProps } from '../model';

customElements.get(WCTAG.Banner) || customElements.define(WCTAG.Banner, BannerComponent);

export function Banner(p: ParentProps<IBannerProps>) {
  const [enums, bools, strs, rest, props] = splitProps(
    mergeProps({ appearance: APPEARANCE.Themed }, p),
    ['appearance'],
    ['closable'],
    ['image'],
    ['children']
  );

  return (
    <wc-banner
      appearance={enums.appearance}
      image={strs.image}
      closable={bools.closable || undefined}
      {...props}
    >
      {rest.children}
    </wc-banner>
  );
}

// packages/preact/src/components/banner/ui/Banner.tsx
import { BannerComponent, IconComponent } from '@otmozorok/wc';
import { WCTAG } from '@otmozorok/wc/consts';
import { IBannerProps } from '../model';

customElements.get(WCTAG.Banner) || customElements.define(WCTAG.Banner, BannerComponent);
customElements.get(WCTAG.Icon) || customElements.define(WCTAG.Icon, IconComponent);

export function Banner({ appearance, image, closable, ...props }: IBannerProps) {
  return (
    <wc-banner
      appearance={appearance}
      image={image}
      closable={closable || undefined}
      {...props}
    ></wc-banner>
  );
}
