// packages/react/src/components/paragraph/ui/Paragraph.tsx
import { ParagraphComponent } from '@otmozorok/wc';
import { WCTAG } from '@otmozorok/wc/consts';
import type { IParagraphProps } from '../model';

customElements.get(WCTAG.Paragraph) || customElements.define(WCTAG.Paragraph, ParagraphComponent);

export function Paragraph({ children, appearance, caps, ...props }: IParagraphProps) {
  return (
    <wc-paragraph appearance={appearance} caps={caps || undefined} {...props}>
      {children}
    </wc-paragraph>
  );
}

// packages/svelte/src/components/paragraph/ui/Paragraph.svelte
<script lang="ts">
  import { ParagraphComponent } from '@otmozorok/wc';
  import { WCTAG } from '@otmozorok/wc/consts';
  import type { IParagraphProps } from '../model';

  customElements.get(WCTAG.Paragraph) || customElements.define(WCTAG.Paragraph, ParagraphComponent);

  const { children, appearance, caps, ...props }: IParagraphProps = $props();
</script>

<wc-paragraph {appearance} caps={caps || undefined} {...props}>
  {@render children?.()}
</wc-paragraph>
