// packages/react/src/components/ellipsis/ui/Ellipsis.tsx
import { EllipsisComponent } from '@otmozorok/wc';
import { WCTAG } from '@otmozorok/wc/consts';
import type { IEllipsisProps } from '../model';

customElements.get(WCTAG.Ellipsis) || customElements.define(WCTAG.Ellipsis, EllipsisComponent);

export function Ellipsis({ maxLines, children, ...props }: IEllipsisProps) {
  return (
    <wc-ellipsis max-lines={maxLines} {...props}>
      {children}
    </wc-ellipsis>
  );
}

// packages/solid/src/components/ellipsis/ui/Ellipsis.tsx
import { EllipsisComponent } from '@otmozorok/wc';
import { WCTAG } from '@otmozorok/wc/consts';
import { mergeProps, type ParentProps, splitProps } from 'solid-js';
import type { IEllipsisProps } from '../model';

customElements.get(WCTAG.Ellipsis) || customElements.define(WCTAG.Ellipsis, EllipsisComponent);

export function Ellipsis(p: ParentProps<IEllipsisProps>) {
  const [enums, rest, props] = splitProps(
    mergeProps({ maxLines: 1 }, p),
    ['maxLines'],
    ['children']
  );

  return (
    <wc-ellipsis max-lines={enums.maxLines} {...props}>
      {rest.children}
    </wc-ellipsis>
  );
}
